### ISSUE TITLE
`Number` support

### ISSUE THREAD

**Issue by nandorojo** [wcandillon/eslint-plugin-reanimated#29]
<img width="1182" alt="Screen Shot 2021-10-28 at 11 42 26 AM" src="https://user-images.githubusercontent.com/13172299/139289927-ea828e13-f801-41a1-a33e-5f500c52ce2a.png">

I believe this code works fine in a worklet

using 1.1.0

**Comment by wcandillon** [comment]
nice, should be fixed in the latest version 🙌🏻

**Comment by nandorojo** [comment]
Amazing, thank you!
