### ISSUE TITLE
`@worklet` directive

### ISSUE THREAD

**Issue by nandorojo** [wcandillon/eslint-plugin-reanimated#31]
<img width="866" alt="Screen Shot 2021-11-01 at 1 22 55 PM" src="https://user-images.githubusercontent.com/13172299/139713193-6ff54d46-01b7-4014-915c-b5d6ccbc5cfb.png">

I'm seeing this error for `formatPrice`, which is a worklet. It's commented like so:

```tsx
/**
 * @worklet
 */
export declare function formatPrice({ value: _value, defaultPrice: _defaultPrice, precision, }: {
    value: string;
    defaultPrice?: string;
    precision?: number;
}): string;
```

I tried changing it to `export declare const`, but that didn't work either. Is there possibly something wrong my my TSDoc comment?

In case it helps, I'm importing `formatPrice` from `react-native-wagmi-charts`.

```ts
import { formatPrice } from 'react-native-wagmi-charts'
```

I tried making a repro on CodeSandbox/Stackblitz, but it doesn't seem like they're configured for custom ESLint configs haha.

**Comment by wcandillon** [comment]
Should be fixed now, let me know if you have any issues.

**Comment by nandorojo** [comment]
Thanks for another quick fix.
